# Generated by Django 2.0.5 on 2018-05-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='магазин')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='store_image/%Y/%m/')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
    ]
