# Generated by Django 2.0.5 on 2018-06-02 08:21

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='image',
        ),
        migrations.AddField(
            model_name='store',
            name='image_store',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='store_image/%Y/%m/'),
        ),
    ]
