# Generated by Django 2.0.5 on 2018-06-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180602_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deal',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
