# Generated by Django 2.0.5 on 2018-05-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20180509_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='image',
            field=models.ImageField(blank=True, upload_to='coupon_image/%Y/%m'),
        ),
    ]
