# Generated by Django 2.0.5 on 2018-05-12 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20180512_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.Store'),
            preserve_default=False,
        ),
    ]
