# Generated by Django 2.0.5 on 2018-05-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_deal_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='скидка'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
