# Generated by Django 2.0.5 on 2018-05-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20180514_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='name',
            field=models.CharField(max_length=250, verbose_name='скидка'),
        ),
    ]
