# Generated by Django 2.0.5 on 2018-05-16 08:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20180514_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
