# Generated by Django 2.0.5 on 2018-05-16 08:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20180516_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
