# Generated by Django 2.0.5 on 2018-05-18 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20180516_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='store',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
