# Generated by Django 2.0.5 on 2018-05-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20180518_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
