# Generated by Django 2.0.5 on 2018-05-21 19:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20180519_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='param',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
