# Generated by Django 2.0.5 on 2018-05-27 15:35

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_deal_param'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='deals_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='deals_images/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='original_picture',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='deal',
            name='vendor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
