# Generated by Django 2.0.5 on 2018-05-27 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20180527_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='original_picture',
        ),
    ]
