# Generated by Django 2.0.5 on 2018-05-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_remove_deal_original_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='deals_image',
            field=models.ImageField(blank=True, upload_to='deals_images/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='vendor',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
