# Generated by Django 2.0.5 on 2018-05-27 18:08

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20180527_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='deals_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='deals_images/%Y/%m'),
        ),
    ]
