# Generated by Django 2.0.5 on 2018-05-27 19:03

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20180527_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='image',
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='coupon_image/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='vendor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
